# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1cc53696a1d64eec2cb78f43deb6b17f15ce499747fccde0694e8d16ca336913af89bb8b00d41bcee52decc927603ef9ef02cf27a77478e2a8308b6608dd9359

test:
  secret_key_base: 545569d8f89a1980534b32ee28ab686b87c2596d0ca4240560fcbca0f0fcdb42110b26b7ff181d742f74c6e7d4738e1f2dccf9605007781c76bb755a10817b21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
